document Vertex macro loading and modifying
HackerN64/F3DEX3 pull request #15
Opened 2024-07-01 02:24 UTC by coco875

2024-07-02 03:16 UTC, ariahiro64 commented
vertex value flag tells the microcode to use packed normals in f3dex3 so it does have a big meaning

2024-07-02 13:01 UTC, coco875 commented
I just copy from n64 official doc can you give a phrase to replace with I don't know so much this feature

2024-07-02 13:06 UTC, coco875 commented
@ariahiro64 I change it with what somone suggest in the discord it's correct now ?

2024-07-08 04:37 UTC, sauraen requested changes

2024-07-08 04:37 UTC, sauraen commented on gbi.h
> + * not recommended to use, won't work if
The end of this comment got moved to the next macro. It was originally a multiline comment across two definitions.

2024-07-08 04:37 UTC, sauraen commented on gbi.h
> + * It loads an internal vertex buffer in the RSP with points that are used by @ref gSP1Triangle macros to generate polygons. This vertex cache can hold up to 16 vertices, and the vertex loading can b
Change 16 to `56 (F3DEX3)`

2024-07-08 04:37 UTC, sauraen commented on gbi.h
> + * The range of n or v0 has been changed along with the change in vertex cache size. The number of vertices which can be loaded at once is less than 56, so it is necessary to split the load when load
Please remove this line, this was SGI documentation for a limitation which was removed long before F3DEX3 (where you could load fewer vertices at a time than you could store in total). EX3 has 56 verts and you can load any set of them at once up to all 56.

2024-07-08 04:37 UTC, sauraen commented on gbi.h
> + * Because the RSP geometry transformation engine uses a vertex list with triangle list architecture, it is quite powerful. A simple one-triangle macro retains maximum performance.
I don't know what SGI was exactly comparing this to, but the statement `A simple one-triangle macro retains maximum performance.` is not true today, that is the least performant compared to SP2Triangles or the new 5 tris commands in EX3.

2024-07-08 04:37 UTC, sauraen commented on gbi.h
> + * @param v0 is the load vertex by index vo(0~15) in vertex buffer
Please update this to 0-55

2024-07-08 04:37 UTC, sauraen commented on gbi.h
> + * @param vtx specifies which of the RSP's vertices (0-15) to modify
Please update this to 0-55

2024-07-08 04:37 UTC, sauraen commented on gbi.h
> + * This is an advanced macro. You need a good understanding of how vertices work in the RSP microcode before you use this macro (refer to gSPVertex). The range of vtx has been changed with as the ver
Please remove `The range of vtx has been changed with as the vertex cache increased. Its range is now the same as that for gSPVertex.`, this is again referring to old limitations pre-F3DEX.

2024-07-08 13:51 UTC, coco875 commented
I fix all comment you made I don't know so much about F3DEX this include modification you made for F3DEX3 (for 56 vertices I just forget x))

2024-07-10 03:38 UTC, sauraen approved these changes

2024-07-10 03:38 UTC, merged